### ISSUE TITLE
Constructor DescripcionMedio

### ISSUE THREAD

**Issue by GLizaso** [GLizaso/TP-Fundamentos-de-Inform-tica#2]
https://github.com/GLizaso/TP-Fundamentos-de-Inform-tica/blob/d42f5fc306d6857d4dfd9846d0bcd65f6c34ccdd/Quimica.py#L234

Está bien hecha esta asociación de fórmula con el compuesto en la construcción de la clase?

**Comment by clombardi** [comment]
Auch, no, no está bien, por una sutileza. Cuando hacés 
  `compuestoAux = CompuestoAux(Compuesto(compuesto), cant)`
estás creando un nuevo compuesto vacío, sin átomos ni enlaces. 

En el constructor de DescripcionMedio lo único que podés hacer es recordar las fórmulas, y la cantidad de veces que aparece cada fórmula. Después, fijate que en casi todos los métodos de la clase `DescripcionMedio` te llega un compuesto por parámetro. Ahí tenés que fijarte si entre las fórmulas que tenés en la descripción, alguna es la fórmula del compuesto que te pasan por parámetro. 

P.ej. en la pregunta `molesCompuesto(agua)` del enunciado, **en el método molesCompuesto** se le pide la fórmula al compuesto, y se compara esa fórmula con las que están registradas en la Descripcion. Hay una con dos moles, OK, por eso la respuesta es `2`.

**Comment by GLizaso** [comment]
Corregido y andando!!
