### ISSUE TITLE
Test proporcionElementoSobreMasa en test_compuesto 

### ISSUE THREAD

**Issue by GLizaso** [GLizaso/TP-Fundamentos-de-Inform-tica#4]
AssertionError: 17 != 15

¿Error en cuenta?

**Comment by clombardi** [comment]
Hola Georgina, el enunciado es correcto. La masa molar del amoníaco en el modelo debe ser 17 (lo que además se corresponde con la teoría, recién googleé): son 14 por el átomo de nitrógeno, más 3 que corresponden a los 3 átomos de hidrógeno. Dado lo que hiciste, la forma más fácil de corregir es en el método masaElemento en la clase ElementoConAtomo: ahí hay que multiplicar el peso atómico del elemento por la cantidad de átomos. P.ej. la masaElemento del hidrógeno en el amoníaco es 3, no 1. Y ahí se corrige el test.

**Comment by GLizaso** [comment]
Excelente! Solucionado.

**Comment by clombardi** [comment]
Qué bueno!
